hydra:
  run:
    dir: ${output_dir}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    root: null
    disable_existing_loggers: false
  job_logging:
    version: 1
    root: null
    disable_existing_loggers: false
  env: {}
  mode: RUN
  searchpath:
  - file:///new_world/cockatiel/TeleNas/DataExchange/yuling/Flow-Planner/flow_planner/run_script
  - pkg://nuplan.planning.script.config.common
  - pkg://nuplan.planning.script.experiments
  callbacks: {}
  output_subdir: ${output_dir}/code/hydra
  overrides:
    hydra:
    - hydra.searchpath=[file:///new_world/cockatiel/TeleNas/DataExchange/yuling/Flow-Planner/flow_planner/run_script,pkg://nuplan.planning.script.config.common,pkg://nuplan.planning.script.experiments]
    - hydra.mode=RUN
    task:
    - +simulation=closed_loop_nonreactive_agents
    - planner=safeflow_planner
    - planner.safeflow_planner.ckpt_path=/new_world/cockatiel/TeleNas/DataExchange/yuling/safeflow-nuplan-transfer/dmpc_fm_cbf/notebooks/cache/model_vel_5ch_canonical_r.pt
    - planner.safeflow_planner.safeflow_project_root=/new_world/cockatiel/TeleNas/DataExchange/yuling/safeflow-nuplan-transfer/dmpc_fm_cbf
    - planner.safeflow_planner.device=cpu
    - planner.safeflow_planner.fm_num_segments=8
    - planner.safeflow_planner.ode_method=rk4
    - planner.safeflow_planner.model_trajectory_steps=60
    - planner.safeflow_planner.use_cbf=true
    - scenario_builder=nuplan_mini
    - scenario_builder.db_files=/new_world/cockatiel/TeleNas/DataExchange/yuling/nuplan-devkit/nuplan-v1.1_mini/data/cache/mini/2021.07.24.20.37.45_veh-17_00015_00375.db
    - scenario_filter=all_scenarios
    - scenario_filter.scenario_types=[starting_left_turn]
    - scenario_filter.scenario_tokens=[d9ee9cf40a84520f]
    - scenario_filter.map_names=[us-nv-las-vegas-strip]
    - scenario_filter.num_scenarios_per_type=1
    - scenario_filter.limit_total_scenarios=1
    - experiment_uid=safeflow/all_scenarios/fm_cbf/model_vel_5ch_canonical_r_2026-09-17-13-17-43
    - worker=sequential
    - number_of_cpus_allocated_per_simulation=1
    - number_of_gpus_allocated_per_simulation=0
    - distributed_mode=SINGLE_NODE
    - enable_simulation_progress_bar=true
    - verbose=true
    - planner.safeflow_planner.enable_overtake_demo=false
    - planner.safeflow_planner.force_overtake_demo=false
  job:
    name: run_simulation
    chdir: null
    override_dirname: +simulation=closed_loop_nonreactive_agents,distributed_mode=SINGLE_NODE,enable_simulation_progress_bar=true,experiment_uid=safeflow/all_scenarios/fm_cbf/model_vel_5ch_canonical_r_2026-09-17-13-17-43,number_of_cpus_allocated_per_simulation=1,number_of_gpus_allocated_per_simulation=0,planner.safeflow_planner.ckpt_path=/new_world/cockatiel/TeleNas/DataExchange/yuling/safeflow-nuplan-transfer/dmpc_fm_cbf/notebooks/cache/model_vel_5ch_canonical_r.pt,planner.safeflow_planner.device=cpu,planner.safeflow_planner.enable_overtake_demo=false,planner.safeflow_planner.fm_num_segments=8,planner.safeflow_planner.force_overtake_demo=false,planner.safeflow_planner.model_trajectory_steps=60,planner.safeflow_planner.ode_method=rk4,planner.safeflow_planner.safeflow_project_root=/new_world/cockatiel/TeleNas/DataExchange/yuling/safeflow-nuplan-transfer/dmpc_fm_cbf,planner.safeflow_planner.use_cbf=true,planner=safeflow_planner,scenario_builder.db_files=/new_world/cockatiel/TeleNas/DataExchange/yuling/nuplan-devkit/nuplan-v1.1_mini/data/cache/mini/2021.07.24.20.37.45_veh-17_00015_00375.db,scenario_builder=nuplan_mini,scenario_filter.limit_total_scenarios=1,scenario_filter.map_names=[us-nv-las-vegas-strip],scenario_filter.num_scenarios_per_type=1,scenario_filter.scenario_tokens=[d9ee9cf40a84520f],scenario_filter.scenario_types=[starting_left_turn],scenario_filter=all_scenarios,verbose=true,worker=sequential
    id: ???
    num: ???
    config_name: default_simulation
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /new_world/cockatiel/TeleNas/DataExchange/yuling/Flow-Planner/flow_planner/run_script
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /new_world/cockatiel/TeleNas/DataExchange/yuling/nuplan-devkit/nuplan/planning/script/config/simulation
      schema: file
      provider: main
    - path: /new_world/cockatiel/TeleNas/DataExchange/yuling/Flow-Planner/flow_planner/run_script
      schema: file
      provider: hydra.searchpath in command-line
    - path: nuplan.planning.script.config.common
      schema: pkg
      provider: hydra.searchpath in command-line
    - path: nuplan.planning.script.experiments
      schema: pkg
      provider: hydra.searchpath in command-line
    - path: ''
      schema: structured
      provider: schema
    output_dir: /tmp/safeflow_many_vehicle_traffic/exp/simulation/closed_loop_nonreactive_agents/safeflow/all_scenarios/fm_cbf/model_vel_5ch_canonical_r_2026-09-17-13-17-43
    choices:
      simulation: closed_loop_nonreactive_agents
      simulation_time_controller: step_simulation_time_controller
      planner: safeflow_planner
      ego_controller: two_stage_controller
      ego_controller/motion_model: kinematic_bicycle_model
      ego_controller/tracker: lqr_tracker
      observation: box_observation
      splitter: nuplan
      simulation_metric: simulation_closed_loop_nonreactive_agents
      worker: sequential
      model: null
      scenario_filter: all_scenarios
      scenario_builder: nuplan_mini
      scenario_builder/scenario_mapping: nuplan_scenario_mapping
      scenario_builder/vehicle_parameters: nuplan_vehicle_parameters
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: none
      hydra/hydra_logging: none
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
