[project]
name = "fmtorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "torch>=2.7.0",
    "torchdiffeq>=0.2.5",
    "torchvision>=0.22.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "celluloid>=0.2.0",
    "jupyter>=1.1.1",
]

[tool.setuptools]
packages = ["fmtorch"]
